### ISSUE TITLE
Make tree from json

### ISSUE THREAD

**Issue by ddkwork** [Zstorm999/CIDER#3]
Hello,i will load json for make tree,but if the json field is array, the (tree node)key will be repeated,how can i do?thank you. Sorry my bad english.

{
  "group<1>": {
    "binary<1>": "game/system/session/info",
    "packed<2>": {
      "group<2>": [
        {
          "varint<1>": 0,
          "binary<2>": "d3048a459417e6c0b7d39c971b99a58029f2720f7b2a70c992c826ce48184069",
          "binary<3>": "6593D03B-92BC-4BC6-BF54-D16BB0271AF9",
          "binary<4>": "Apple-iPhone10,3"
        },
        {
          "varint<1>": 1,
          "binary<2>": "",
          "binary<3>": "EAAIe5YPC68wBAPGE5l7JEtIE9BfPQmbcpQ92b0c9fD29vKn5ZCwHkutEjpX2PEcvyBLDqo15gNi1x0VN7U6d26QDaABEDaVzu3vuZBYKtvHH130O9Kna4742s6B8dtr1aKJUw7HuuyNWObpWYZCqBDGvypB7Js93oBISkwWrjbuYZAooY5vHLHFPyuIcLAcV8ZAX9sRFn3un18KZA0MEuDtgekU4ZBTJ1doEQmQ4DCLXwZDZD"
        }
      ],
      "binary<3>": "6593D03B-92BC-4BC6-BF54-D16BB0271AF9"
    },
    "varint<3>": 0,
    "binary<4>": "",
    "varint<5>": 0
  }
}

**Comment by Zstorm999** [comment]
Are you sure this is the right place to ask this question ? I did not do anything JSON-related in this project. 

I’m not sure if I actually understand your question. Go is a statically typed language, you cannot create data structures "on the fly", reading it from JSON as you would in javascript. 
For your information : https://golangr.com/read-json-file/
